---
- name: clean work directory
  file:
    path: '{{ work_dir }}'
    state: absent

- name: make work directory
  file:
    path: '{{ work_dir }}'
    state: directory
    mode: '0755'

- name: copy test files
  copy:
    src: '../../../{{ item.src }}'
    dest: '{{ work_dir }}'
  with_items:
    - { src: 'benchmark' }
    - { src: 'conftest.py' }

- name: set requirements.txt
  with_items:
    - config: requirements.txt
      d: '{{ work_dir }}'
  template:
    src: '{{ item.config }}.j2'
    dest: '{{ item.d }}/{{ item.config }}'
    mode: '{{ item.m|default("0644") }}'

- name: create virtual env
  pip:
    requirements: '{{work_dir}}/requirements.txt'
    virtualenv: '{{ venv_dir }}'
    state: forcereinstall
    virtualenv_command: /usr/bin/python3.8 -m venv

- name: set pytest.ini
  with_items:
    - config: pytest.ini
      d: '{{ work_dir }}'
  template:
    src: '{{ item.config }}.j2'
    dest: '{{ item.d }}/{{ item.config }}'
    mode: '{{ item.m|default("0644") }}'


